/*
    GENERAL
*/
export const FETCH_GENERAL = 'FETCH_GENERAL';
export const FETCH_GENERAL_SUCCESS = 'FETCH_GENERAL_SUCCESS';
export const FETCH_GENERAL_FAILED = 'FETCH_GENERAL_FAILED';

/*
    COUNTRIES' DATA
*/
export const FETCH_ALL_COUNTRIES = 'FETCH_ALL_COUNTRIES';
export const FETCH_ALL_COUNTRIES_SUCCESS = 'FETCH_ALL_COUNTRIES_SUCCESS';
export const FETCH_ALL_COUNTRIES_FAILURE = 'FETCH_ALL_COUNTRIES_FAILURE';

/*
    SPECIFIC-COUNTRIES' DATA
*/
export const FETCH_COUNTRY_DATA = 'FETCH_COUNTRY_DATA';
export const FETCH_COUNTRY_DATA_SUCCESS = 'FETCH_COUNTRY_DATA_SUCCESS';
export const FETCH_COUNTRY_DATA_FAILED = 'FETCH_COUNTRY_DATA_FAILED';
export const FETCH_VACCINE_COUNTRY_SUCCESS = 'FETCH_VACCINE_COUNTRY_SUCCESS';

/*
    HISTORICAL DATA
*/
export const FETCH_HISTORICAL_DATA = 'FETCH_HISTORICAL_DATA';
export const FETCH_HISTORICAL_ONE_WEEK_SUCCESS =
  'FETCH_HISTORICAL_ONE_WEEK_SUCCESS';
export const FETCH_HISTORICAL_TWO_WEEKS_SUCCESS =
  'FETCH_HISTORICAL_TWO_WEEKS_SUCCESS';
export const FETCH_HISTORICAL_ONE_MONTH_SUCCESS =
  'FETCH_HISTORICAL_ONE_MONTH_SUCCESS';
export const FETCH_HISTORICAL_DATA_FAILURE = 'FETCH_HISTORICAL_DATA_FAILURE';
export const FETCH_HISTORICAL_COUNTRY_SUCCESS =
  'FETCH_HISTORICAL_COUNTRY_SUCCESS';
